#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

apt update
apt install -y nginx

echo "Hello World!" > /var/www/html/index.html
service nginx restart
