#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 8?
# configures nginx to run and listen to port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
echo "" > /run/nginx.pid
